// Direct language switching without complex context
export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
];

export const TRANSLATIONS = {
  en: {
    'legalDisclaimer': 'Legal Disclaimer',
    'reviewAcceptDisclaimer': 'Review and accept the legal disclaimer and terms',
    'startBuildingSwms': 'Start Building Your SWMS',
    'createComprehensiveDocumentation': 'Create comprehensive safety documentation tailored to your industry and project requirements.',
    'quickActions': 'Quick Actions',
    'manageSafetyCompliance': 'Manage your Safe Work Method Statements and safety compliance',
    'draftSwms': 'Draft SWMS',
    'saveCompleteLater': 'Save and complete later',
    'completedSwms': 'Completed SWMS',
    'projectSpecificDocumentation': 'Project-specific documentation',
    'createNewSwms': 'Create New SWMS',
    'quickStart': 'Quick Start',
    'recentSwmsDocuments': 'Recent SWMS Documents',
    'viewAll': 'View All',
    'nav.dashboard': 'Dashboard',
    'nav.swms-builder': 'SWMS Builder',
    'nav.ai-generator': 'AI SWMS Generator',
    'nav.my-swms': 'My SWMS',
    'nav.safety-library': 'Safety Library',
    'nav.team': 'Team',
    'nav.analytics': 'Analytics',
    'nav.account': 'Account',
    'btn.save': 'Save',
    'btn.cancel': 'Cancel',
    'btn.next': 'Next',
    'btn.generate': 'Generate SWMS',
    'swms.builder': 'SWMS Builder',
    'swms.create.comprehensive': 'Create comprehensive safety documentation',
    'swms.back.dashboard': 'Back to Dashboard',
    'swms.save.close': 'Save & Close',
    'swms.step': 'Step',
    'swms.of': 'of',
    'swms.progress': 'Progress',
    'swms.complete': 'Complete',
    'swms.step1.title': 'Project & Contractor Details',
    'swms.step1.desc': 'Project information, contractor details, and high-risk work identification',
    'swms.step2.title': 'Work Activities & Risk Assessment',
    'swms.step2.desc': 'Detailed work breakdown and comprehensive risk assessments',
    'swms.step3.title': 'Plant, Equipment & Training',
    'swms.step3.desc': 'Equipment specifications, training requirements, and permits',
    'swms.step4.title': 'Emergency & Monitoring',
    'swms.step4.desc': 'Emergency procedures and review/monitoring processes',
    'swms.step5.title': 'Legal Disclaimer',
    'swms.step5.desc': 'Accept terms and liability disclaimer',
    'swms.step6.title': 'Final Document',
    'swms.step6.desc': 'Generate complete SWMS document',
    'swms.title': 'SWMS Title',
    'swms.trade.type': 'Trade Type',
    'swms.trade.select': 'Select your trade',
    'swms.job.name': 'Job Name',
    'swms.job.number': 'Job Number',
    'swms.project.address': 'Project Address',
    'swms.project.location': 'Project Location/Description',
    'legalDisclaimerTerms': 'Legal Disclaimer Terms',
  },
  zh: {
    'legalDisclaimer': '法律免责声明',
    'reviewAcceptDisclaimer': '审查并接受法律免责声明和条款',
    'startBuildingSwms': '开始构建您的SWMS',
    'createComprehensiveDocumentation': '创建针对您的行业和项目要求的综合安全文档。',
    'quickActions': '快捷操作',
    'manageSafetyCompliance': '管理您的安全工作方法声明和安全合规性',
    'draftSwms': '草稿SWMS',
    'saveCompleteLater': '保存并稍后完成',
    'completedSwms': '已完成的SWMS',
    'projectSpecificDocumentation': '项目特定文档',
    'createNewSwms': '创建新的SWMS',
    'quickStart': '快速开始',
    'recentSwmsDocuments': '最近的SWMS文档',
    'viewAll': '查看全部',
    'nav.dashboard': '仪表板',
    'nav.swms-builder': 'SWMS构建器',
    'nav.ai-generator': 'AI SWMS生成器',
    'nav.my-swms': '我的SWMS',
    'nav.safety-library': '安全库',
    'nav.team': '团队',
    'nav.analytics': '分析',
    'nav.account': '账户',
    'btn.save': '保存',
    'btn.cancel': '取消',
    'btn.next': '下一个',
    'btn.generate': '生成SWMS',
    'swms.builder': 'SWMS构建器',
    'swms.create.comprehensive': '创建全面的安全文档',
    'swms.back.dashboard': '返回仪表板',
    'swms.save.close': '保存并关闭',
    'swms.step': '步骤',
    'swms.of': '共',
    'swms.progress': '进度',
    'swms.complete': '完成',
    'swms.step1.title': '项目和承包商详情',
    'swms.step1.desc': '项目信息、承包商详情和高风险工作识别',
    'swms.step2.title': '工作活动和风险评估',
    'swms.step2.desc': '详细的工作分解和全面的风险评估',
    'swms.step3.title': '设备、机械和培训',
    'swms.step3.desc': '设备规格、培训要求和许可证',
    'swms.step4.title': '应急和监控',
    'swms.step4.desc': '应急程序和审查/监控流程',
    'swms.step5.title': '法律免责声明',
    'swms.step5.desc': '接受条款和责任免责声明',
    'swms.step6.title': '最终文档',
    'swms.step6.desc': '生成完整的SWMS文档',
    'swms.title': 'SWMS标题',
    'swms.trade.type': '行业类型',
    'swms.trade.select': '选择您的行业',
    'swms.job.name': '工作名称',
    'swms.job.number': '工作编号',
    'swms.project.address': '项目地址',
    'swms.project.location': '项目位置/描述',
    'legalDisclaimerTerms': '法律免责声明条款',
  },
  es: {
    'legalDisclaimer': 'Descargo de Responsabilidad Legal',
    'reviewAcceptDisclaimer': 'Revisar y aceptar el descargo de responsabilidad legal y los términos',
    'startBuildingSwms': 'Comenzar a Construir Su SWMS',
    'createComprehensiveDocumentation': 'Crear documentación de seguridad integral adaptada a los requisitos de su industria y proyecto.',
    'quickActions': 'Acciones Rápidas',
    'manageSafetyCompliance': 'Gestione sus Declaraciones de Método de Trabajo Seguro y cumplimiento de seguridad',
    'draftSwms': 'Borrador SWMS',
    'saveCompleteLater': 'Guardar y completar más tarde',
    'completedSwms': 'SWMS Completados',
    'projectSpecificDocumentation': 'Documentación específica del proyecto',
    'createNewSwms': 'Crear Nuevo SWMS',
    'quickStart': 'Inicio Rápido',
    'recentSwmsDocuments': 'Documentos SWMS Recientes',
    'viewAll': 'Ver Todo',
    'nav.dashboard': 'Panel de Control',
    'nav.swms-builder': 'Constructor SWMS',
    'nav.ai-generator': 'Generador AI SWMS',
    'nav.my-swms': 'Mis SWMS',
    'nav.safety-library': 'Biblioteca de Seguridad',
    'nav.team': 'Equipo',
    'nav.analytics': 'Análisis',
    'nav.account': 'Cuenta',
    'btn.save': 'Guardar',
    'btn.cancel': 'Cancelar',
    'btn.next': 'Siguiente',
    'btn.generate': 'Generar SWMS',
    'swms.builder': 'Constructor SWMS',
    'swms.create.comprehensive': 'Crear documentación de seguridad integral',
    'swms.back.dashboard': 'Volver al Panel',
    'swms.save.close': 'Guardar y Cerrar',
    'swms.step': 'Paso',
    'swms.of': 'de',
    'swms.progress': 'Progreso',
    'swms.complete': 'Completo',
    'swms.step1.title': 'Detalles del Proyecto y Contratista',
    'swms.step1.desc': 'Información del proyecto, detalles del contratista e identificación de trabajo de alto riesgo',
    'swms.step2.title': 'Actividades de Trabajo y Evaluación de Riesgos',
    'swms.step2.desc': 'Desglose detallado del trabajo y evaluaciones integrales de riesgos',
    'swms.step3.title': 'Planta, Equipo y Entrenamiento',
    'swms.step3.desc': 'Especificaciones de equipo, requisitos de entrenamiento y permisos',
    'swms.step4.title': 'Emergencia y Monitoreo',
    'swms.step4.desc': 'Procedimientos de emergencia y procesos de revisión/monitoreo',
    'swms.step5.title': 'Descargo de Responsabilidad Legal',
    'swms.step5.desc': 'Aceptar términos y descargo de responsabilidad',
    'swms.step6.title': 'Documento Final',
    'swms.step6.desc': 'Generar documento SWMS completo',
    'swms.title': 'Título SWMS',
    'swms.trade.type': 'Tipo de Oficio',
    'swms.trade.select': 'Seleccione su oficio',
    'swms.job.name': 'Nombre del Trabajo',
    'swms.job.number': 'Número de Trabajo',
    'swms.project.address': 'Dirección del Proyecto',
    'swms.project.location': 'Ubicación/Descripción del Proyecto',
    'legalDisclaimerTerms': 'Términos del Descargo de Responsabilidad Legal',
  }
};

// Global language state
let currentLang = 'en';

export function getCurrentLanguage(): string {
  return currentLang;
}

export function setLanguage(lang: string): void {
  currentLang = lang;
  localStorage.setItem('app-language', lang);
  window.location.reload(); // Force page refresh to apply translations
}

export function translate(key: string): string {
  const langTranslations = TRANSLATIONS[currentLang as keyof typeof TRANSLATIONS];
  return (langTranslations as any)?.[key] || (TRANSLATIONS.en as any)[key] || key;
}

// Initialize language from localStorage
try {
  const saved = localStorage.getItem('app-language');
  if (saved && LANGUAGES.find(l => l.code === saved)) {
    currentLang = saved;
  }
} catch {
  currentLang = 'en';
}