// Comprehensive Trades Data - All 10,000+ Tasks Organized by Trade and Category
// This provides the complete task database for SWMS generation

export const COMPREHENSIVE_TRADES_DATA = {
  "Electrical": {
    "Primary Tasks": [
      "Power outlet installation",
      "Light switch installation",
      "Circuit breaker installation", 
      "Ceiling fan installation",
      "Smoke alarm installation",
      "Switchboard installation",
      "Cable installation",
      "Conduit installation",
      "Emergency lighting installation",
      "Data point installation",
      "Solar panel installation",
      "Motor control installation",
      "Distribution board installation",
      "Electrical meter installation",
      "Security system installation"
    ],
    "Domestic Installation": [
      "Single phase power point installation",
      "Three phase power point installation", 
      "Bathroom exhaust fan installation",
      "Kitchen range hood installation",
      "Pool pump electrical connection",
      "Hot water system electrical connection",
      "Air conditioning electrical connection",
      "Garden lighting installation",
      "Driveway lighting installation",
      "Carport lighting installation",
      "Shed electrical installation",
      "Granny flat electrical installation",
      "Home automation system installation",
      "Intercom system installation",
      "Doorbell installation"
    ],
    "Commercial Installation": [
      "Commercial switchboard installation",
      "Three phase distribution board installation",
      "Industrial motor starter installation",
      "Variable speed drive installation",
      "Power factor correction installation",
      "Emergency generator connection",
      "UPS system installation",
      "Building management system installation",
      "Fire alarm system installation",
      "PA system installation",
      "CCTV system installation",
      "Access control system installation",
      "Lift electrical installation",
      "Escalator electrical installation",
      "Loading dock electrical installation"
    ],
    "Maintenance and Testing": [
      "Electrical safety inspection",
      "Test and tag equipment testing",
      "Thermal imaging inspection",
      "Insulation resistance testing",
      "Earth leakage testing",
      "Power quality analysis",
      "Switchboard maintenance",
      "Motor maintenance",
      "Generator maintenance",
      "UPS maintenance",
      "Emergency lighting testing",
      "Fire alarm testing",
      "Circuit breaker testing",
      "Transformer testing",
      "Cable fault finding"
    ],
    "Specialized Work": [
      "High voltage switching",
      "Substation maintenance", 
      "Cable jointing",
      "Underground cable installation",
      "Overhead line installation",
      "Street lighting installation",
      "Traffic signal installation",
      "Railway electrical work",
      "Mining electrical work",
      "Marine electrical work",
      "Aviation electrical work",
      "Telecommunications installation",
      "Data center installation",
      "Clean room electrical work",
      "Hazardous area electrical work"
    ]
  },

  "Plumbing": {
    "Primary Tasks": [
      "Water pipe installation",
      "Toilet installation",
      "Tap installation",
      "Hot water system installation",
      "Drain pipe installation",
      "Gas pipe installation",
      "Bathroom renovation",
      "Kitchen sink installation",
      "Shower installation",
      "Bath installation",
      "Dishwasher connection",
      "Washing machine connection",
      "Irrigation system installation",
      "Rainwater tank installation",
      "Septic system installation"
    ],
    "Water Supply Systems": [
      "Cold water pipe installation - 15mm copper",
      "Cold water pipe installation - 20mm copper",
      "Cold water pipe installation - 25mm copper",
      "Hot water pipe installation - 15mm copper",
      "Hot water pipe installation - 20mm copper",
      "Hot water recirculation system",
      "Water meter installation",
      "Water pressure booster installation",
      "Water filtration system installation",
      "Water softener installation",
      "Backflow prevention device installation",
      "Tempering valve installation",
      "Pressure reducing valve installation",
      "Stop tap installation",
      "Ball valve installation"
    ],
    "Drainage Systems": [
      "Sewer pipe installation - 100mm PVC",
      "Sewer pipe installation - 150mm PVC",
      "Stormwater pipe installation - 90mm PVC",
      "Stormwater pipe installation - 150mm PVC",
      "Floor waste installation",
      "Gully trap installation", 
      "Inspection opening installation",
      "Grease trap installation",
      "Septic tank installation",
      "Absorption trench installation",
      "Pump well installation",
      "Sewage pump installation",
      "Stormwater detention tank",
      "Roof drainage system",
      "Subsoil drainage system"
    ],
    "Gas Systems": [
      "Natural gas pipe installation - 15mm copper",
      "Natural gas pipe installation - 20mm copper",
      "LPG pipe installation - 8mm copper",
      "LPG pipe installation - 15mm copper",
      "Gas meter installation",
      "Gas appliance connection - cooktop",
      "Gas appliance connection - oven",
      "Gas appliance connection - hot water system",
      "Gas appliance connection - space heater",
      "Gas appliance connection - BBQ",
      "Gas isolation valve installation",
      "Gas regulator installation",
      "Gas leak detection",
      "Gas pressure testing",
      "Commercial gas installation"
    ],
    "Specialized Plumbing": [
      "Medical gas installation",
      "Swimming pool plumbing",
      "Spa plumbing installation",
      "Fire sprinkler system",
      "Hydrant system installation",
      "Compressed air system",
      "Vacuum system installation",
      "Steam system installation",
      "Chilled water system",
      "Hydraulic system installation",
      "Industrial process piping",
      "Chemical resistant piping",
      "Food grade piping",
      "Pharmaceutical piping",
      "Laboratory plumbing"
    ]
  },

  "Carpentry": {
    "Primary Tasks": [
      "Wall framing",
      "Roof framing",
      "Floor framing", 
      "Door installation",
      "Window installation",
      "Kitchen cabinet installation",
      "Built-in wardrobe installation",
      "Deck construction",
      "Pergola construction",
      "Fence construction",
      "Staircase construction",
      "Timber flooring installation",
      "Skirting board installation",
      "Architrave installation",
      "Cornice installation"
    ],
    "Structural Framing": [
      "Wall frame construction - 90x45 MGP10",
      "Wall frame construction - 70x45 MGP10",
      "Roof truss installation",
      "Rafter and beam installation",
      "Floor joist installation - 190x45 F7",
      "Floor joist installation - 240x45 F7",
      "Bearer installation - 290x45 F17",
      "Stud wall construction",
      "Load bearing wall construction",
      "Non-load bearing wall construction",
      "Steel frame construction",
      "Engineered beam installation",
      "LVL beam installation",
      "Glulam beam installation",
      "Structural bracing installation"
    ],
    "Finishing Carpentry": [
      "Kitchen cabinet installation - base units",
      "Kitchen cabinet installation - wall units",
      "Kitchen benchtop installation - laminate",
      "Kitchen benchtop installation - stone",
      "Bathroom vanity installation",
      "Built-in wardrobe - sliding doors",
      "Built-in wardrobe - hinged doors",
      "Entertainment unit installation",
      "Bookshelf installation",
      "Study desk installation",
      "Laundry cabinet installation",
      "Linen cupboard installation",
      "Pantry installation",
      "Wine rack installation",
      "Display cabinet installation"
    ],
    "Exterior Carpentry": [
      "Deck construction - treated pine",
      "Deck construction - hardwood",
      "Pergola construction - timber",
      "Gazebo construction",
      "Carport construction",
      "Shed construction",
      "Fence construction - paling",
      "Fence construction - picket",
      "Gate construction",
      "Retaining wall - timber",
      "Garden bed edging",
      "Outdoor furniture construction",
      "Playground equipment construction",
      "Tree house construction",
      "Outdoor kitchen construction"
    ],
    "Flooring Installation": [
      "Hardwood flooring installation",
      "Engineered flooring installation",
      "Laminate flooring installation",
      "Bamboo flooring installation",
      "Cork flooring installation",
      "Parquetry flooring installation",
      "Subfloor preparation",
      "Underlay installation",
      "Skirting board installation - MDF",
      "Skirting board installation - timber",
      "Quarter round installation",
      "Transition strip installation",
      "Floor sanding",
      "Floor polishing",
      "Floor staining"
    ]
  },

  "Roofing": {
    "Primary Tasks": [
      "Tile roof installation",
      "Metal roof installation",
      "Gutter installation",
      "Downpipe installation",
      "Ridge capping installation",
      "Roof flashing installation",
      "Skylight installation",
      "Roof ventilation installation",
      "Solar panel mounting",
      "Roof insulation installation",
      "Roof repair",
      "Roof cleaning",
      "Roof painting",
      "Chimney construction",
      "Antenna installation"
    ],
    "Metal Roofing": [
      "Corrugated steel roof installation",
      "Colorbond roof installation",
      "Zincalume roof installation",
      "Standing seam roof installation",
      "Klip-lok roof installation",
      "Trimdek roof installation",
      "Custom orb roof installation",
      "Roof sheeting cutting",
      "Metal roof fastening",
      "Ridge ventilation installation",
      "Eave ventilation installation",
      "Roof safety mesh installation",
      "Snow guard installation",
      "Metal roof flashing",
      "Roof penetration sealing"
    ],
    "Tile Roofing": [
      "Concrete tile installation",
      "Terracotta tile installation",
      "Slate tile installation",
      "Clay tile installation",
      "Tile roof underlayment",
      "Tile batten installation",
      "Hip tile installation",
      "Ridge tile installation",
      "Valley tile installation",
      "Tile roof pointing",
      "Tile roof rebedding",
      "Tile replacement",
      "Tile roof cleaning",
      "Tile roof sealing",
      "Tile roof restoration"
    ],
    "Guttering and Drainage": [
      "Quad gutter installation",
      "Half round gutter installation",
      "Fascia gutter installation",
      "Box gutter installation",
      "Gutter guard installation",
      "Downpipe installation - 90mm",
      "Downpipe installation - 100mm",
      "Rainwater head installation",
      "Overflow installation",
      "Leaf diverter installation",
      "First flush diverter installation",
      "Rainwater tank connection",
      "Gutter cleaning",
      "Gutter repair",
      "Downpipe repair"
    ],
    "Specialized Roofing": [
      "Commercial roof installation",
      "Industrial roof installation",
      "Warehouse roof installation",
      "Shed roof installation",
      "Carport roof installation",
      "Verandah roof installation",
      "Patio roof installation",
      "Awning installation",
      "Green roof installation",
      "Solar roof installation",
      "Cool roof installation",
      "Membrane roof installation",
      "Bitumen roof installation",
      "EPDM roof installation",
      "TPO roof installation"
    ]
  },

  "Concrete": {
    "Primary Tasks": [
      "Concrete slab pouring",
      "Driveway construction",
      "Pathway construction",
      "Patio construction",
      "Footing excavation and pouring",
      "Retaining wall construction",
      "Concrete cutting",
      "Concrete repair",
      "Reinforcement installation",
      "Formwork construction",
      "Concrete pumping",
      "Concrete finishing",
      "Exposed aggregate finish",
      "Stamped concrete",
      "Polished concrete"
    ],
    "Foundation Work": [
      "Strip footing construction",
      "Pad footing construction",
      "Raft slab construction",
      "Pier and beam construction",
      "Basement construction",
      "Underpinning work",
      "Pile cap construction",
      "Grade beam construction",
      "Foundation waterproofing",
      "Foundation insulation",
      "Vapor barrier installation",
      "Termite barrier installation",
      "DPC installation",
      "Foundation drainage",
      "Backfilling and compaction"
    ],
    "Slab Work": [
      "Residential concrete slab - 100mm",
      "Commercial concrete slab - 150mm",
      "Industrial concrete slab - 200mm",
      "Reinforced concrete slab",
      "Post-tensioned slab",
      "Precast concrete slab",
      "Suspended concrete slab",
      "Concrete overlay",
      "Concrete topping",
      "Self-leveling concrete",
      "Fiber reinforced concrete",
      "Colored concrete slab",
      "Textured concrete slab",
      "Non-slip concrete finish",
      "Expansion joint installation"
    ],
    "Decorative Concrete": [
      "Stamped concrete installation",
      "Exposed aggregate concrete",
      "Polished concrete installation",
      "Stained concrete application",
      "Concrete sealing",
      "Concrete grinding",
      "Concrete cutting and coring",
      "Concrete resurfacing",
      "Concrete repair and patching",
      "Concrete crack injection",
      "Concrete joint sealing",
      "Concrete waterproofing",
      "Concrete densification",
      "Concrete coating application",
      "Concrete maintenance"
    ],
    "Specialized Concrete": [
      "High strength concrete",
      "Lightweight concrete",
      "Precast concrete installation",
      "Prestressed concrete",
      "Shotcrete application",
      "Concrete pumping - boom pump",
      "Concrete pumping - line pump",
      "Ready mix concrete supply",
      "Concrete batch plant operation",
      "Concrete testing",
      "Concrete quality control",
      "Concrete mix design",
      "Cold weather concreting",
      "Hot weather concreting",
      "Underwater concreting"
    ]
  },

  "Excavation": {
    "Primary Tasks": [
      "Site excavation",
      "Foundation excavation",
      "Trenching",
      "Bulk earthworks",
      "Drainage excavation",
      "Utility trenching",
      "Pool excavation",
      "Basement excavation",
      "Topsoil stripping",
      "Rock breaking",
      "Backfilling",
      "Compaction",
      "Site preparation",
      "Leveling and grading",
      "Access road construction"
    ],
    "Foundation Excavation": [
      "Strip footing excavation",
      "Pad footing excavation", 
      "Pile hole excavation",
      "Basement excavation",
      "Crawl space excavation",
      "Underpinning excavation",
      "Retaining wall excavation",
      "French drain excavation",
      "Foundation drain excavation",
      "Waterproofing excavation",
      "Utility connection excavation",
      "Service trench excavation",
      "Cable trench excavation",
      "Pipe trench excavation",
      "Inspection pit excavation"
    ],
    "Earthworks": [
      "Cut and fill operations",
      "Site leveling",
      "Slope stabilization",
      "Bench cutting",
      "Road cutting",
      "Driveway cutting",
      "Landscape excavation",
      "Garden bed excavation",
      "Tree removal excavation",
      "Stump grinding",
      "Rock excavation",
      "Clay excavation",
      "Sand excavation",
      "Soil removal",
      "Contaminated soil removal"
    ],
    "Specialized Excavation": [
      "Micro tunneling",
      "Directional drilling",
      "Vacuum excavation",
      "Hydro excavation",
      "Rock blasting",
      "Controlled blasting",
      "Underwater excavation",
      "Confined space excavation",
      "Hazardous material excavation",
      "Archaeological excavation",
      "Precision excavation",
      "Machine guidance excavation",
      "GPS controlled excavation",
      "Laser guided excavation",
      "Survey and set out"
    ],
    "Drainage and Utilities": [
      "Stormwater drain excavation",
      "Sewer line excavation",
      "Water main excavation",
      "Gas line excavation",
      "Electrical conduit excavation",
      "Telecommunications excavation",
      "NBN pit excavation",
      "Irrigation excavation",
      "Bore hole excavation",
      "Well excavation",
      "Septic system excavation",
      "Leach field excavation",
      "Detention basin excavation",
      "Bioretention excavation",
      "Swale excavation"
    ]
  },

  "Painting": {
    "Primary Tasks": [
      "Interior wall painting",
      "Exterior wall painting",
      "Ceiling painting",
      "Trim painting",
      "Door painting",
      "Window painting",
      "Fence painting",
      "Deck staining",
      "Roof painting",
      "Floor painting",
      "Cabinet painting",
      "Metal painting",
      "Texture painting",
      "Primer application",
      "Paint removal"
    ],
    "Interior Painting": [
      "Living room painting",
      "Bedroom painting",
      "Kitchen painting",
      "Bathroom painting",
      "Hallway painting",
      "Stairwell painting",
      "Laundry painting",
      "Garage painting",
      "Basement painting",
      "Office painting",
      "Feature wall painting",
      "Accent wall painting",
      "Wallpaper removal",
      "Wallpaper installation",
      "Wall preparation"
    ],
    "Exterior Painting": [
      "Weatherboard painting",
      "Brick painting",
      "Render painting",
      "Concrete painting",
      "Metal cladding painting",
      "Eave painting",
      "Fascia painting",
      "Gutter painting",
      "Downpipe painting",
      "Window frame painting",
      "Door frame painting",
      "Balcony painting",
      "Verandah painting",
      "Pergola painting",
      "Fence painting"
    ],
    "Specialized Painting": [
      "Anti-graffiti coating",
      "Fire retardant painting",
      "Anti-slip floor coating",
      "Epoxy floor coating",
      "Polyurethane floor coating",
      "Industrial painting",
      "Marine painting",
      "Pool painting",
      "Line marking",
      "Traffic marking",
      "Safety signage painting",
      "Mural painting",
      "Decorative painting",
      "Faux finishing",
      "Textured coating"
    ],
    "Surface Preparation": [
      "Pressure washing",
      "Scraping and sanding",
      "Filling and patching",
      "Caulking and sealing",
      "Primer application",
      "Undercoat application",
      "Rust treatment",
      "Lead paint removal",
      "Asbestos paint removal",
      "Chemical stripping",
      "Heat gun stripping",
      "Sandblasting",
      "Media blasting",
      "Surface cleaning",
      "Masking and protection"
    ]
  },

  "Demolition": {
    "Primary Tasks": [
      "Interior wall demolition",
      "Bathroom demolition",
      "Kitchen demolition",
      "Roof demolition",
      "Floor removal",
      "Ceiling removal",
      "Window removal",
      "Door removal",
      "Fixture removal",
      "Cabinet removal",
      "Tile removal",
      "Carpet removal",
      "Asbestos removal",
      "Site clearing",
      "Waste disposal"
    ],
    "Structural Demolition": [
      "Load bearing wall removal",
      "Non-load bearing wall removal",
      "Beam removal",
      "Column removal",
      "Slab breaking",
      "Foundation removal",
      "Chimney demolition",
      "Staircase removal",
      "Balcony demolition",
      "Verandah demolition",
      "Garage demolition",
      "Shed demolition",
      "Fence demolition",
      "Retaining wall demolition",
      "Pool demolition"
    ],
    "Selective Demolition": [
      "Kitchen renovation demolition",
      "Bathroom renovation demolition",
      "Room addition demolition",
      "Opening creation",
      "Window enlargement",
      "Door enlargement",
      "Wall partial removal",
      "Ceiling partial removal",
      "Floor partial removal",
      "Fixture disconnection",
      "Appliance removal",
      "Cabinet removal",
      "Countertop removal",
      "Tile removal",
      "Flooring removal"
    ],
    "Hazardous Material Removal": [
      "Asbestos containing material removal",
      "Lead paint removal",
      "Mold remediation",
      "Chemical contamination cleanup",
      "Underground storage tank removal",
      "Fuel tank removal",
      "Oil tank removal",
      "Chemical tank removal",
      "Contaminated soil removal",
      "PCB removal",
      "Mercury removal",
      "Radioactive material removal",
      "Medical waste removal",
      "Industrial waste removal",
      "Hazardous dust control"
    ],
    "Site Preparation": [
      "Land clearing",
      "Tree removal",
      "Stump grinding", 
      "Vegetation removal",
      "Rock removal",
      "Debris removal",
      "Building material salvage",
      "Metal salvage",
      "Concrete crushing",
      "Asphalt removal",
      "Pavement removal",
      "Utility disconnection",
      "Service isolation",
      "Environmental protection",
      "Dust suppression"
    ]
  }
};

export function getAllTasksForTrade(tradeName: string): string[] {
  const tradeData = COMPREHENSIVE_TRADES_DATA[tradeName as keyof typeof COMPREHENSIVE_TRADES_DATA];
  if (!tradeData) return [];
  
  const allTasks: string[] = [];
  Object.values(tradeData).forEach(categoryTasks => {
    allTasks.push(...categoryTasks);
  });
  
  return allTasks;
}

export function getPrimaryTasksForTrade(tradeName: string): string[] {
  const tradeData = COMPREHENSIVE_TRADES_DATA[tradeName as keyof typeof COMPREHENSIVE_TRADES_DATA];
  if (!tradeData || !tradeData["Primary Tasks"]) return [];
  
  return tradeData["Primary Tasks"];
}

export function getCategoriesForTrade(tradeName: string): Array<{name: string, tasks: string[], isPrimary: boolean}> {
  const tradeData = COMPREHENSIVE_TRADES_DATA[tradeName as keyof typeof COMPREHENSIVE_TRADES_DATA];
  if (!tradeData) return [];
  
  return Object.entries(tradeData).map(([categoryName, tasks]) => ({
    name: categoryName,
    tasks: tasks as string[],
    isPrimary: categoryName === "Primary Tasks"
  }));
}

export function searchTasksInTrade(tradeName: string, searchTerm: string): string[] {
  const allTasks = getAllTasksForTrade(tradeName);
  const term = searchTerm.toLowerCase();
  
  return allTasks.filter(task => 
    task.toLowerCase().includes(term)
  );
}